// src/modules/suppression/suppression.service.ts
//
// Generates signed unsubscribe tokens for the hosted endpoint.
// Each token links a specific domain to a specific recipient.
// Tokens are HMAC-signed so they cannot be forged or guessed.

import crypto from "crypto";
import db from "../../db";

// ─────────────────────────────────────────────
// GENERATE AN UNSUBSCRIBE TOKEN
// Called when a user sends a campaign and needs
// List-Unsubscribe headers for each recipient
// ─────────────────────────────────────────────

export async function generateUnsubscribeToken(
  tenantId: string,
  domainId: string,
  recipientEmail: string,
): Promise<string> {
  // Validate inputs
  if (!recipientEmail || !recipientEmail.includes("@")) {
    throw new Error("Invalid recipient email address");
  }

  // Normalize the email to lowercase
  const normalizedEmail = recipientEmail.toLowerCase().trim();

  // Create HMAC signature using the secret key
  // HMAC = Hash-based Message Authentication Code
  // This proves the token was generated by InboxRules
  // and has not been tampered with
  const secret = process.env.UNSUB_HMAC_SECRET;

  if (!secret || secret.length < 32) {
    throw new Error(
      "UNSUB_HMAC_SECRET must be at least 32 characters. " +
        "Generate one with: openssl rand -hex 32",
    );
  }

  // The token signs both the domain and the recipient
  // so the token is unique per domain+recipient pair
  const tokenPayload = `${domainId}:${normalizedEmail}`;
  const token = crypto
    .createHmac("sha256", secret)
    .update(tokenPayload)
    .digest("hex");

  // Hash the token before storing in the database
  // If the database is compromised, attackers cannot use the hashes
  const tokenHash = crypto.createHash("sha256").update(token).digest("hex");

  // Hash the recipient email for storage
  // We never store plain email addresses
  const recipientHash = crypto
    .createHash("sha256")
    .update(normalizedEmail)
    .digest("hex");

  // Store the token record — upsert so duplicate calls are idempotent
  await db.unsubscribeToken.upsert({
    where: { tokenHash },
    create: {
      tenantId,
      domainId,
      tokenHash,
      recipientHash,
    },
    update: {
      // If token already exists, just update the timestamp
      // This handles the case where the same email is added to a campaign twice
    },
  });

  return token;
}

// ─────────────────────────────────────────────
// BUILD LIST-UNSUBSCRIBE HEADERS
// Returns the exact header values to add to an email
// ─────────────────────────────────────────────

export async function buildUnsubscribeHeaders(
  tenantId: string,
  domainId: string,
  domain: string,
  recipientEmail: string,
): Promise<{
  listUnsubscribe: string;
  listUnsubscribePost: string;
}> {
  const token = await generateUnsubscribeToken(
    tenantId,
    domainId,
    recipientEmail,
  );

  // The unsubscribe URL points to our Cloudflare Worker
  const unsubUrl = `${process.env.UNSUB_WORKER_URL || "https://unsub.inboxrules.io"}/unsubscribe/${token}`;

  return {
    // List-Unsubscribe must include BOTH a URL and a mailto: address
    // Gmail and Yahoo require both for full compliance
    listUnsubscribe: `<${unsubUrl}>, <mailto:unsubscribe@${domain}?subject=unsubscribe>`,

    // List-Unsubscribe-Post is required for RFC 8058 one-click compliance
    // This exact string is required — do not change it
    listUnsubscribePost: "List-Unsubscribe=One-Click",
  };
}

// ─────────────────────────────────────────────
// CHECK IF AN EMAIL IS SUPPRESSED
// Used before sending to verify the recipient
// has not previously unsubscribed
// ─────────────────────────────────────────────

export async function isEmailSuppressed(
  tenantId: string,
  recipientEmail: string,
): Promise<boolean> {
  const normalizedEmail = recipientEmail.toLowerCase().trim();

  const recipientHash = crypto
    .createHash("sha256")
    .update(normalizedEmail)
    .digest("hex");

  const event = await db.suppressionEvent.findFirst({
    where: {
      tenantId,
      emailHash: recipientHash,
      eventType: { in: ["unsubscribe", "spam_complaint"] },
    },
  });

  return event !== null;
}
